name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Debug
        run: echo "${{ github.head_ref }}"
      - name: Run Playwright tests
        if: ${{ !startsWith(github.head_ref, 'update-snapshots/') }}
        run: npm run test:e2e
      - name: Update snapshots
        if: ${{ startsWith(github.head_ref, 'update-snapshots/') }}
        run: npm run update-snapshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
